apiVersion: v1
kind: Service
metadata:
  name: aperag-console
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
  selector:
    app: aperag-console
