config:
  type: object
  properties:
    admin_user_exists:
      type: boolean
      description: Whether the admin user exists
    auth:
      type: object
      properties:
        type:
          type: string
          enum: [none, auth0, authing, logto, cookie]
        auth0:
          type: object
          properties:
            auth_domain:
              type: string
            auth_app_id:
              type: string
        authing:
          type: object
          properties:
            auth_domain:
              type: string
            auth_app_id:
              type: string
        logto:
          type: object
          properties:
            auth_domain:
              type: string
            auth_app_id:
              type: string
    login_methods:
      type: array
      items:
        type: string
      description: Available login methods
      example: ["local", "google", "github"]
