"""empty message

Revision ID: 4e9e9050d8db
Revises: d112e0332219
Create Date: 2025-09-20 11:46:07.116100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9e9050d8db'
down_revision: Union[str, None] = 'd112e0332219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_marketplace',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('bot_id', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', name='uq_bot_marketplace_bot')
    )
    op.create_index('idx_bot_marketplace_bot_id', 'bot_marketplace', ['bot_id'], unique=False)
    op.create_index('idx_bot_marketplace_gmt_deleted', 'bot_marketplace', ['gmt_deleted'], unique=False)
    op.create_index('idx_bot_marketplace_list', 'bot_marketplace', ['status', 'gmt_created'], unique=False)
    op.create_index('idx_bot_marketplace_status', 'bot_marketplace', ['status'], unique=False)
    op.create_index(op.f('ix_bot_marketplace_gmt_deleted'), 'bot_marketplace', ['gmt_deleted'], unique=False)
    op.create_table('user_bot_subscription',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('bot_marketplace_id', sa.String(length=24), nullable=False),
    sa.Column('gmt_subscribed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bot_marketplace_id', 'gmt_deleted', name='idx_user_bot_marketplace_history_unique')
    )
    op.create_index('idx_user_bot_subscription_gmt_deleted', 'user_bot_subscription', ['gmt_deleted'], unique=False)
    op.create_index('idx_user_bot_subscription_marketplace', 'user_bot_subscription', ['bot_marketplace_id'], unique=False)
    op.create_index('idx_user_bot_subscription_user', 'user_bot_subscription', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_bot_subscription_gmt_deleted'), 'user_bot_subscription', ['gmt_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bot_subscription_gmt_deleted'), table_name='user_bot_subscription')
    op.drop_index('idx_user_bot_subscription_user', table_name='user_bot_subscription')
    op.drop_index('idx_user_bot_subscription_marketplace', table_name='user_bot_subscription')
    op.drop_index('idx_user_bot_subscription_gmt_deleted', table_name='user_bot_subscription')
    op.drop_table('user_bot_subscription')
    op.drop_index(op.f('ix_bot_marketplace_gmt_deleted'), table_name='bot_marketplace')
    op.drop_index('idx_bot_marketplace_status', table_name='bot_marketplace')
    op.drop_index('idx_bot_marketplace_list', table_name='bot_marketplace')
    op.drop_index('idx_bot_marketplace_gmt_deleted', table_name='bot_marketplace')
    op.drop_index('idx_bot_marketplace_bot_id', table_name='bot_marketplace')
    op.drop_table('bot_marketplace')
    # ### end Alembic commands ###
